version: '3.9'
services:
  frontend:
    container_name: bot-frontend
    image: bot-frontend:1.0.1
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - '8000:8000'
    environment:
      - db_user=vpomo
      - db_pass=admin
      - db_name=okx-bot
      - db_host=db
    depends_on:
      - db
    networks:
      - postgres
  backend:
    container_name: bot-backend
    image: bot-backend:1.0.1
    build:
      dockerfile: backend.Dockerfile
    ports:
      - '8020:8020'
    environment:
      - db_user=vpomo
      - db_pass=admin
      - db_name=okx-bot
      - db_host=db
    depends_on:
      - db
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pgdata: {}