version: "3.8"
services:
  frontend:
    container_name: bot-frontend
    image: bot-frontend:1.0.1
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - '8000:8000'
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      TOKEN_PASSWORD: ${TOKEN_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    networks:
      - postgres
  backend:
    container_name: bot-backend
    image: bot-backend:1.0.1
    restart: always
    build:
      dockerfile: backend.Dockerfile
    ports:
      - '8020:8020'
    networks:
      - postgres


networks:
  postgres:
    driver: bridge
