version: "3.8"
services:
  frontend:
    container_name: bot-frontend
    image: bot-frontend:1.0.1
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - '8000:8000'
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      okx_api_passphrase: ${okx_api_passphrase}
      okx_api_key: ${okx_api_key}
      okx_api_secret_key: ${okx_api_secret_key}
    networks:
      - postgres
  backend:
    container_name: bot-backend
    image: bot-backend:1.0.1
    build:
      dockerfile: backend.Dockerfile
    ports:
      - '8020:8020'
    networks:
      - postgres


networks:
  postgres:
    driver: bridge
