name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: docker-compose
        run: docker compose build && docker compose up -d
