name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: docker-compose
        run: docker compose kill && docker compose rm && docker compose up -d
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          okx_api_passphrase: ${{ secrets.okx_api_passphrase }}
          okx_api_key: ${{ secrets.okx_api_key }}
          okx_api_secret_key: ${{ secrets.okx_api_secret_key }}
