name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Run Container
        run: docker compose up -d --build
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          okx_api_passphrase: ${{ secrets.okx_api_passphrase }}
          okx_api_key: ${{ secrets.okx_api_key }}
          okx_api_secret_key: ${{ secrets.okx_api_secret_key }}

      - name: Cleanup Unused Images
        run: docker image prune -f
